# Restore old style debuginfo creation for rpm >= 4.14.
%undefine _debugsource_packages
%undefine _debuginfo_subpackages

# -*- rpm-spec -*-
BuildRoot:      %_topdir/solver-0.1.0.0-Linux-aarch64
Summary:        solver application package
Name:           solver
Version:        0.1.0.0
Release:        1
License:        Apache-2.0
Group:          Development/Tools
Vendor:         Formatter Inc.















Prefix: /usr





%define _rpmdir %_topdir/RPMS
%define _srcrpmdir %_topdir/SRPMS
%define _rpmfilename solver-0.1.0.0-Linux-aarch64.rpm
%define _unpackaged_files_terminate_build 0





%description
Solver application package.

This package contains the solver binary built from the Formatter Inc. training project.
The solver application uses formatter_ex and solver_lib static libraries.


# This is a shortcutted spec file generated by CMake RPM generator
# we skip _install step because CPack does that for us.
# We do only save CPack installed tree in _prepr
# and then restore it in build.
%prep
mv $RPM_BUILD_ROOT %_topdir/tmpBBroot

%install
if [ -e $RPM_BUILD_ROOT ];
then
  rm -rf $RPM_BUILD_ROOT
fi
mv %_topdir/tmpBBroot $RPM_BUILD_ROOT



%clean








%files
%defattr(-,root,root,-)
/usr/bin/solver




%changelog
* Sat May 02 2026 eroshinpetr <eroshinpetr1@gmail.com> 0.1.0.0
- Initial solver package release



